#%RAML 1.0
title: Myclouddeployment
/sample:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {
                "message":"Success"
              }